#pragma once

#include "./geometry.h"

struct CoordinateFrame {
    GeodeticPosition origin;
    double meters_per_degree_lon = 0.0;
    double meters_per_degree_lat = 0.0;
};

struct GeographicBounds {
    double degrees_N;
    double degrees_S;
    double degrees_E;
    double degrees_W;

    bool contains(double lon, double lat) const;
};

/*******************************************************************************
 * A position on the Earth's surface defined by a latitude (north/south), 
 * longitude (east/west), and ellipsoidal height (elevation). This is not a 
 * Cartesian coordinate and should not be stored in Vec3. Longitude and latitude 
 * are angular values (degrees), while elevation is linear (meters).
 ******************************************************************************/
struct GeodeticPosition {

    // Longitude in decimal degrees east
    double longitude = 0.0;
    
    // Latitude in decimal degrees north
    double latitude = 0.0;  
    
    // Depth below the surface (NEGATIVE DOWNWARD)
    double elevation = 0.0;     
};

using LocalPosition = Vec3;
LocalPosition geodetic_to_local(GeodeticPosition position, CoordinateFrame frame);

/*******************************************************************************
 * A sounding is the specific, calculated depth point generated by a single 
 * valid beam. Invalid and null beams should be filtered out when extracting 
 * soundings from a ping. The original flag is retained for diagnostics only.
 ******************************************************************************/
struct Sounding {

    // Position calculated by the beam
    GeodeticPosition position;

    // Beam's zero-based index within the ping.
    std::size_t beam_index = 0; 

    // MB-System beam-quality flag (valid, null etc.)
    char beam_flag = 0;         
};

/*******************************************************************************
 * Metadata for a single sonar ping fired by the multi-beam sonar sensor. 
 * Consists of multiple narrow, directional beams arranged in a wide, 
 * fan-shaped pattern covering a "swath" of the seafloor.
 ******************************************************************************/
struct Ping {

    // Unix seconds (epoch time)
    double timestamp = 0.0; 

    // Position of the sonar/navigation reference point at ping time
    GeodeticPosition sensor_position;
};

/*******************************************************************************
 * Metadata for one swath-sonar file. Contains multiple pings collected by the 
 * sensor at different times and positions. Pings should be processed 
 * incrementally rather than being retained in memory.
 ******************************************************************************/
struct SwathFile {

    // Path to swath file
    std::string path;    

    // MB-System format identifier
    int format = 0;           
};

/******************************************************************************/

CollectedPointCloud read_datalist(std::string datatlist_path) {
    CollectedPointCloud collected_point_cloud{};
    // datalist entry
    //      ↓
    // open one swath file
    //      ↓
    // read one ping into MB-System buffers
    //      ↓
    // convert each valid beam directly to CollectedPoint
    //      ↓
    // reuse buffers for next ping
    //      ↓
    // close file and continue
    return collected_point_cloud;
}
